import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import axios from 'axios';
import Head from 'next/head';
import Todo from '../components/Todo';
import { useForm, SubmitHandler } from 'react-hook-form';
import toast from 'react-hot-toast';
type TodoType = {
  task: string;
};

export default function Home() {
  const queryClient = useQueryClient();

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<TodoType>();

  const query = useQuery(['todo'], async () => {
    const response = await axios.get('/api/todo');
    return response;
  });

  const todos = query?.data?.data?.todos;

  const onSubmit = (data: TodoType) => {
    addTodoMutation.mutate(data);
  };

  const createTodo = async (data: TodoType) => {
    const res = await axios.post('/api/todo', data);
    if (res.data.message) {
      toast.error(res.data.message);
    } else {
      toast.success('task added Successfully!');
      return res;
    }
  };

  const addTodoMutation = useMutation(createTodo, {
    onSuccess: () => {
      queryClient.invalidateQueries();
    },
  });

  return (
    <>
      <Head>
        <title>TODOS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="mt-5 pt-5">
        <div className="container my-2">
          <div className="row">
            <div className="col-md-4 m-auto py-1">
              <form onSubmit={handleSubmit(onSubmit)}>
                <div className="input-group mb-3">
                  <input
                    type="text"
                    className="form-control"
                    placeholder="Todo text"
                    aria-describedby="addTodo"
                    {...register('task', { required: true })}
                  />
                  <button
                    className="btn btn-outline-secondary"
                    type="submit"
                    id="addTodo"
                  >
                    Add Todo
                  </button>
                </div>
              </form>
              {todos?.map((_item: any, index: any) => (
                // console.log(_item)
                <div key={_item.id + 1}>
                  <Todo item={_item} index={index} />
                </div>
              ))}
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
